server:
  port: 36542
#  undertow:

#logger
logging:
  config: classpath:log4j2-spring.xml

spring:
  profiles:
    active: dev
  application:
    name: cloud-client
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: "GMT+8"
  http:
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:36541/eureka/

feign.hystrix.enabled: true