server:
  port: 36542
#  undertow:

info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    environment: ${spring.profiles.active}

spring:
  profiles:
    active: dev
  application:
    name: ${rentalba.clients.name}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: "GMT+8"
  http:
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://cloud-register:36541/eureka/

feign.hystrix.enabled: true